name: 'Linting'
on:
  push: {}
  pull_request: {}

jobs:
  job:
    name: check-clang-format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        extensions: 'h,c'
        clangFormatVersion: 16
